version: '3'

services:
  pythonapi:
    build: pythonapi/
    ports:
      - 5000:5000
    networks:
      - deploy_network
    container_name: pythonapi

  streamlitapi:
    build: streamlitapi/
    depends_on:
      - pythonapi
    ports:
        - 8501:8501
    networks:
      - deploy_network
    container_name: streamlitapi

networks:
  deploy_network:
    driver: bridge
